version: v1
host: http-echo.cluster-test.com

blueGreen:
  enabled: true
  version: "{{ .Values.version }}"
  deleteOldVersion: true
  deleteOriginal: true
  minReplicas: 2
  extraCommand: []
  service:
    clusterIP: ""
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  services:
  # - deploymentName: test # required
  #   minReplicas: 1 # defaults blueGreen.minReplicas
  #   serviceName: paket # defaults deploymentName
  - deploymentName: http-echo