apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-blue-green
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-blue-green-role
rules:
- apiGroups: [ "apps" ]
  resources: ["deployments"]
  verbs: [ "get","list","create","delete","patch","watch"]
- apiGroups: [ "autoscaling" ]
  resources: ["horizontalpodautoscalers"]
  verbs: [ "delete","get","create","delete","patch" ]
- apiGroups: [ "" ]
  resources: ["pods"]
  verbs: [ "get","list","watch"]
- apiGroups: [ "" ]
  resources: ["configmaps"]
  verbs: [ "get","list","create","delete","watch"]
- apiGroups: [ "apps" ]
  resources: ["deployments/scale"]
  verbs: [ "update", "get" ]
- apiGroups: [ "" ]
  resources: ["services"]
  verbs: [ "get","patch","create","delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-blue-green-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helm-blue-green-role
subjects:
- kind: ServiceAccount
  name: helm-blue-green
  namespace: {{ .Release.Namespace }}