apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-blue-green.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm-blue-green.fullname" . }}-role
rules:
- apiGroups: [ "autoscaling" ]
  resources: ["horizontalpodautoscalers"]
  verbs: [ "get","list","create","delete" ]
- apiGroups: [ "policy" ]
  resources: ["poddisruptionbudgets"]
  verbs: [ "get","list","create","delete" ]
- apiGroups: [ "apps" ]
  resources: ["deployments"]
  verbs: [ "get","list","create","delete","patch","watch","update"]
- apiGroups: [ "" ]
  resources: ["services","configmaps"]
  verbs: [ "get","list","update","create","delete" ]

- apiGroups: [ "" ]
  resources: ["pods"]
  verbs: [ "get","list","watch"]
- apiGroups: [ "apps" ]
  resources: ["deployments/scale"]
  verbs: [ "update", "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm-blue-green.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm-blue-green.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "helm-blue-green.fullname" . }}
  namespace: {{ .Release.Namespace }}