global:
  imageRegistry: ""

image:
  registry: docker.io
  repository: paskalmaksim/helm-blue-green
  tag: v1.1.1
  pullPolicy: IfNotPresent

nodeSelector: {}
affinity: []
tolerations: []

resources:
  requests:
    cpu: 100m
    memory: 512Mi

version: ""

backoffLimit: 3
activeDeadlineSeconds: 6000
restartPolicy: OnFailure

useDefaultsEnv: true
environment: ""
minReplicas: 2
maxReplicas: 10
minAvailable: 1
maxUnavailable: 0
averageUtilization: 60

config: ""
extraConfig: ""

configPath: "/config/config.yaml"
extraEnv: []
