global:
  imageRegistry: ""

image:
  registry: docker.io
  repository: paskalmaksim/helm-blue-green
  tag: v1.1.0
  pullPolicy: IfNotPresent

nodeSelector: {}
affinity: []
tolerations: []

version: ""

useDefaultsEnv: true
minReplicas: 2
maxReplicas: 10
minAvailable: 1
averageUtilization: 60

config: ""

configPath: "/config/config.yaml"
extraEnv: []
