global:
  imageRegistry: ""

image:
  registry: docker.io
  repository: paskalmaksim/helm-blue-green
  tag: v1.1.2
  pullPolicy: IfNotPresent

priorityClassName: ""
labels: {}
annotations: {}
nodeSelector: {}
affinity: []
tolerations: []

prometheus:
  enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 2Gi

resources:
  requests:
    cpu: 100m
    memory: 512Mi

version: ""

backoffLimit: 3
activeDeadlineSeconds: 6000
restartPolicy: OnFailure

useDefaultsEnv: true
environment: ""
minReplicas: 2
maxReplicas: 10
minAvailable: 1
maxUnavailable: 0
averageUtilization: 60
canaryEnabled: false

config: ""
extraConfig: ""

configPath: "/config/config.yaml"
extraEnv: []
