{{ range .Values.names }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ . }}
spec:
  selector:
    matchLabels:
      app: {{ . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ . }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: http
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        image: hashicorp/http-echo
        args:
        - --text=version=$DEPLOYMENT_VERSION
        ports:
        - containerPort: 5678
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
        readinessProbe:
          tcpSocket:
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
  labels:
    app: {{ . }}
spec:
  type: ClusterIP
  ports:
  - port: 5678
    protocol: TCP
  selector:
    app: {{ . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
data:
  test: "value"
{{ end }}